.TH TEMPREAD 8
.SH NAME
tempRead \- reads a temperature from a file
.SH SYNOPSIS
.B tempRead
[\fB\-v\fR \fiVERBOSE\fr]
[\fB\-d\fR \fIDEVICEID\fR]
.IR Filepath ... 
.SH DESCRIPTION
.B tempRead
Reads string from file representing temperature of one wire sensor
.SH OPTIONS
.TP
.BR \-v ", " \-d =\fIDEVICEID\fR
Set output to max, specify device ID



